import type {
  DayTradeCandidate,
  LongTermOpportunity,
  PortfolioPosition,
  NewsItem,
  WatchlistGroup,
  MarketIndex,
  Alert,
  MarketRegime,
} from '@/types';

export const MARKET_REGIME: MarketRegime = 'Neutral Bullish';

export const MARKET_INDICES: MarketIndex[] = [
  { symbol: 'SPY', name: 'S&P 500 ETF', price: 548.32, change: 4.18, changePercent: 0.77, trend: 'bullish' },
  { symbol: 'QQQ', name: 'Nasdaq 100 ETF', price: 472.14, change: 5.62, changePercent: 1.21, trend: 'bullish' },
  { symbol: 'IWM', name: 'Russell 2000 ETF', price: 214.08, change: -0.94, changePercent: -0.44, trend: 'bearish' },
  { symbol: 'VIX', name: 'Volatility Index', price: 14.72, change: -0.38, changePercent: -2.52, trend: 'bearish' },
  { symbol: 'BTC', name: 'Bitcoin', price: 67480, change: 1240, changePercent: 1.87, trend: 'bullish' },
  { symbol: 'ETH', name: 'Ethereum', price: 3520, change: 78, changePercent: 2.27, trend: 'bullish' },
  { symbol: 'TNX', name: '10Y Yield', price: 4.28, change: 0.03, changePercent: 0.71, trend: 'neutral' },
  { symbol: 'DXY', name: 'Dollar Index', price: 104.32, change: -0.14, changePercent: -0.13, trend: 'bearish' },
];

export const DAY_TRADE_CANDIDATES: DayTradeCandidate[] = [
  {
    id: 'dt-1',
    ticker: 'NVDA',
    company: 'NVIDIA Corporation',
    setupType: 'VWAP Reclaim',
    confidenceScore: 87,
    entryZone: [878.50, 882.00],
    stopLoss: 871.00,
    takeProfits: [892.00, 902.00, 915.00],
    riskReward: 3.2,
    currentPrice: 879.42,
    change: 12.34,
    changePercent: 1.42,
    volume: 48200000,
    relVolume: 2.4,
    float: 2440000000,
    vwap: 876.80,
    atr: 18.50,
    catalystSummary: 'Analyst upgrade to Buy with $1000 PT from Morgan Stanley. AI infrastructure spend accelerating.',
    aiReasoning: 'NVDA reclaimed VWAP after morning dip on 2.4x relative volume. The structure shows institutional accumulation as price holds above the key $875 level. Morgan Stanley upgrade provides fundamental tailwind. Momentum indicators aligning on 5m and 15m suggesting continuation toward prior highs. This is a high-conviction setup with defined risk below the morning low.',
    patternExplanation: 'Classic VWAP reclaim after morning selloff. Price tested $871 key support, bounced cleanly on volume, and reclaimed VWAP at $876. Pattern suggests institutions used the dip as accumulation opportunity.',
    vwapBehavior: 'Price crossed above VWAP at 10:42 AM on 3x average volume. VWAP is now acting as support with two successful tests. Bullish VWAP positioning confirmed.',
    structureAnalysis: 'Higher lows forming on 5m chart. 15m shows intact uptrend from open. Support cluster at $871-875 held on three tests. Structure is constructive.',
    volumeAnalysis: 'Relative volume at 2.4x daily average. Volume surge on reclaim confirms institutional buying. No distribution patterns visible.',
    keyRisks: ['Broad market weakness could invalidate setup', 'Any negative AI-sector news', 'Stop below $871 must be respected'],
    regimeCompatibility: 'Highly compatible with current Neutral Bullish regime. Mega-cap tech outperforming.',
    momentumStrength: 88,
    liquidityScore: 95,
    structureScore: 85,
    catalystScore: 82,
    sector: 'Technology',
    preMarketHigh: 884.50,
    preMarketLow: 869.20,
  },
  {
    id: 'dt-2',
    ticker: 'META',
    company: 'Meta Platforms',
    setupType: 'Bull Flag',
    confidenceScore: 81,
    entryZone: [512.00, 515.50],
    stopLoss: 506.00,
    takeProfits: [524.00, 532.00, 542.00],
    riskReward: 2.8,
    currentPrice: 513.20,
    change: 8.75,
    changePercent: 1.74,
    volume: 22400000,
    relVolume: 1.8,
    float: 2570000000,
    vwap: 509.40,
    atr: 12.20,
    catalystSummary: 'Threads user growth beats estimates. AI Llama 3 adoption accelerating.',
    aiReasoning: 'META has formed a textbook bull flag on the 5-minute chart after a strong opening drive. The consolidation shows tight price action above VWAP with declining volume on the pause, which is constructive. The catalyst of Threads growth provides fundamental support for the move. Entry on flag breakout with stop below flag support offers excellent risk management.',
    patternExplanation: 'Strong pole move from open ($504 to $518), followed by orderly 45-minute consolidation between $511-$515. This tight range with declining volume is the flag formation.',
    vwapBehavior: 'Price has been trading above VWAP all session. VWAP rising toward flag support, providing additional support layer.',
    structureAnalysis: 'Consolidation above prior resistance at $511. 15m trend intact. Higher timeframe momentum strong from earnings gap.',
    volumeAnalysis: '1.8x relative volume. Volume declining on consolidation (healthy). Expecting volume expansion on breakout above $515.50.',
    keyRisks: ['Flag invalidated on break below $508', 'Sector rotation out of tech', 'Market-wide selloff'],
    regimeCompatibility: 'Strong compatibility. Bull flags perform best in Neutral Bullish to Bullish regimes.',
    momentumStrength: 82,
    liquidityScore: 92,
    structureScore: 88,
    catalystScore: 75,
    sector: 'Technology',
    preMarketHigh: 519.00,
    preMarketLow: 502.50,
  },
  {
    id: 'dt-3',
    ticker: 'SMCI',
    company: 'Super Micro Computer',
    setupType: 'Opening Range Breakout',
    confidenceScore: 74,
    entryZone: [892.00, 896.00],
    stopLoss: 882.00,
    takeProfits: [912.00, 926.00, 945.00],
    riskReward: 2.5,
    currentPrice: 893.50,
    change: 24.80,
    changePercent: 2.85,
    volume: 8900000,
    relVolume: 3.1,
    float: 52000000,
    vwap: 885.20,
    atr: 28.40,
    catalystSummary: 'New AI server partnership announced. Insider buying activity detected.',
    aiReasoning: 'SMCI showing exceptional relative strength with 3.1x relative volume. The opening range breakout above $892 is significant as this level was prior resistance. Float of 52M creates potential for explosive moves. Insider buying adds conviction. Setup scores well on structure but carries higher risk due to higher ATR and smaller float. Position sizing must be adjusted.',
    patternExplanation: 'Opening range established between $875-$892 in first 30 minutes. Breakout above $892 with significant volume. Classic ORB setup.',
    vwapBehavior: 'Currently extended above VWAP. Watch for VWAP pullback as potential re-entry. Initial position on breakout.',
    structureAnalysis: 'ORB breakout on 1m and 5m. Need 15m close above $892 to confirm. Structure is bullish.',
    volumeAnalysis: '3.1x relative volume on breakout. Strong institutional footprint. Volume distribution positive.',
    keyRisks: ['High ATR means wider stops required', 'Smaller float = higher volatility', 'Hot AI sector could face rotation'],
    regimeCompatibility: 'Compatible but requires tighter risk management due to float characteristics.',
    momentumStrength: 91,
    liquidityScore: 68,
    structureScore: 78,
    catalystScore: 80,
    sector: 'Technology',
    preMarketHigh: 905.00,
    preMarketLow: 868.00,
  },
  {
    id: 'dt-4',
    ticker: 'TSLA',
    company: 'Tesla Inc.',
    setupType: 'Fair Value Gap',
    confidenceScore: 66,
    entryZone: [248.00, 251.50],
    stopLoss: 243.00,
    takeProfits: [259.00, 268.00, 278.00],
    riskReward: 2.1,
    currentPrice: 249.80,
    change: -3.20,
    changePercent: -1.27,
    volume: 89400000,
    relVolume: 1.3,
    float: 3180000000,
    vwap: 253.40,
    atr: 9.80,
    catalystSummary: 'Cybertruck delivery update scheduled. FSD progress report anticipated.',
    aiReasoning: 'TSLA has a fair value gap on the 15m chart from $248-$252. Price is currently filling this gap from below. Setup scores 66 — watchlist quality. The setup is valid but multiple concerns: trading below VWAP, mixed sector narrative, and below-average relative volume limit conviction. Monitor for VWAP reclaim before considering entry.',
    patternExplanation: 'FVG created on gap down at open. Price filling gap from lower end. Pattern quality is moderate.',
    vwapBehavior: 'Price below VWAP — negative positioning. VWAP at $253.40 is overhead resistance. Need VWAP reclaim for higher conviction.',
    structureAnalysis: 'Mixed structure. Downward bias on 15m but potential reversal at support. Watch closely.',
    volumeAnalysis: 'Only 1.3x relative volume — below ideal threshold. Needs volume confirmation.',
    keyRisks: ['Below VWAP is major concern', 'Low relative volume', 'Macro headwinds for consumer discretionary'],
    regimeCompatibility: 'Marginal — consumer discretionary underperforming in current regime.',
    momentumStrength: 52,
    liquidityScore: 98,
    structureScore: 58,
    catalystScore: 62,
    sector: 'Consumer Discretionary',
    preMarketHigh: 255.00,
    preMarketLow: 244.50,
  },
];

export const LONG_TERM_OPPORTUNITIES: LongTermOpportunity[] = [
  {
    id: 'lt-1',
    ticker: 'NVDA',
    company: 'NVIDIA Corporation',
    sector: 'Semiconductors',
    category: 'Strong Compounder',
    opportunityScore: 91,
    entryQuality: 'Neutral Entry',
    currentPrice: 879.42,
    change: 12.34,
    changePercent: 1.42,
    marketCap: '$2.17T',
    targetPrice: 1100,
    upside: 25.1,
    aiThesis: 'NVIDIA has established an unassailable competitive moat in AI compute infrastructure. The CUDA ecosystem represents a decade-long switching cost that competitors cannot replicate in the near term. As enterprises accelerate AI deployments, NVDA\'s data center segment is experiencing demand that structurally exceeds supply — a dynamic that will sustain pricing power and margins. The next 18 months will be defined by Blackwell GPU ramp, sovereign AI spending, and enterprise inference infrastructure buildout.',
    businessModel: 'Fabless semiconductor designer focused on GPUs for gaming, professional visualization, data center AI compute, and automotive. Revenue increasingly recurring through CUDA software ecosystem.',
    growthDrivers: ['Blackwell GPU architecture ramp', 'Sovereign AI national investments', 'Enterprise AI inference infrastructure', 'Automotive AI roadmap', 'Robotics and embodied AI platform'],
    keyRisks: ['Export restrictions on China revenue', 'AMD/Intel competitive response', 'Hyperscaler in-house chip development', 'Valuation compression if growth decelerates'],
    fundamentalScore: 92,
    growthScore: 95,
    valuationScore: 58,
    catalystScore: 88,
    institutionalScore: 91,
    sustainabilityScore: 87,
    aiConfidenceScore: 93,
    riskScore: 72,
    forwardPE: 42.0,
    pegRatio: 0.98,
    evEbitda: 38.5,
    priceToSales: 22.4,
    revenueGrowth: 122,
    marginTrend: 'Expanding — gross margins above 74%',
    insiderActivity: 'Neutral — some insider selling typical at these levels',
    institutionalChange: '+$4.2B institutional inflows last quarter',
    sharaiaCompliant: true,
    analystTarget: 1050,
    analystCount: 42,
  },
  {
    id: 'lt-2',
    ticker: 'PLTR',
    company: 'Palantir Technologies',
    sector: 'Enterprise Software',
    category: 'Institutional Accumulation',
    opportunityScore: 84,
    entryQuality: 'Good Entry',
    currentPrice: 24.82,
    change: 1.14,
    changePercent: 4.81,
    marketCap: '$54B',
    targetPrice: 38,
    upside: 53.1,
    aiThesis: 'Palantir is at a pivotal inflection point. The AIP (Artificial Intelligence Platform) bootcamp model is converting enterprise prospects to customers at unprecedented rates. Government contract backlog remains a durable base, while commercial revenue is accelerating. The market has historically underestimated Palantir\'s total addressable market because it requires deep integration to understand. As enterprise AI spending matures beyond experimentation, PLTR\'s unique data ontology approach becomes the operating system for AI-native enterprises.',
    businessModel: 'Data analytics and AI software platform serving government and enterprise customers. Shifting toward AIP-led commercial growth with high-margin software revenue.',
    growthDrivers: ['AIP enterprise bootcamp conversion pipeline', 'US commercial revenue acceleration', 'Expanded defense and intelligence contracts', 'Maven Smart System deployments', 'International government expansion'],
    keyRisks: ['Government spending cuts or sequestration', 'Sales cycle length in enterprise', 'Competition from hyperscaler AI platforms', 'Dilution from stock compensation'],
    fundamentalScore: 78,
    growthScore: 86,
    valuationScore: 72,
    catalystScore: 82,
    institutionalScore: 84,
    sustainabilityScore: 80,
    aiConfidenceScore: 87,
    riskScore: 68,
    forwardPE: 68.0,
    pegRatio: 1.42,
    evEbitda: 52.0,
    priceToSales: 14.8,
    revenueGrowth: 27,
    marginTrend: 'Improving — first consistent GAAP profitability achieved',
    insiderActivity: 'Positive — CEO Alex Karp reducing selling pace',
    institutionalChange: '+$1.8B institutional accumulation detected',
    sharaiaCompliant: true,
    analystTarget: 32,
    analystCount: 18,
  },
  {
    id: 'lt-3',
    ticker: 'AEHR',
    company: 'Aehr Test Systems',
    sector: 'Semiconductor Equipment',
    category: 'Early Growth Expansion',
    opportunityScore: 78,
    entryQuality: 'Excellent Entry',
    currentPrice: 14.20,
    change: 0.85,
    changePercent: 6.37,
    marketCap: '$580M',
    targetPrice: 28,
    upside: 97.2,
    aiThesis: 'Aehr Test Systems operates in a critical but overlooked segment of the semiconductor supply chain: wafer-level burn-in testing for silicon carbide (SiC) chips. The EV revolution is creating massive demand for SiC power semiconductors, and Aehr holds a near-monopoly position in the burn-in test market for this specific application. The recent pullback from $30+ levels has created an asymmetric opportunity. As EV adoption accelerates globally, the SiC market will require significantly more Aehr equipment. This is exactly the type of picks-and-shovels infrastructure play that institutional investors accumulate quietly before retail discovers it.',
    businessModel: 'Manufactures test and burn-in equipment for semiconductors, with dominant market share in silicon carbide wafer testing for EV power management chips.',
    growthDrivers: ['SiC semiconductor demand explosion from EV adoption', 'Monopolistic market position in SiC burn-in testing', 'New customer wins from tier-1 automotive supply chain', 'AI chip testing expansion opportunity', 'International semiconductor fab buildout'],
    keyRisks: ['EV adoption pace slower than expected', 'Customer concentration risk', 'Lumpy revenue from capital equipment orders', 'New entrants in SiC testing market'],
    fundamentalScore: 74,
    growthScore: 88,
    valuationScore: 85,
    catalystScore: 76,
    institutionalScore: 72,
    sustainabilityScore: 82,
    aiConfidenceScore: 80,
    riskScore: 60,
    forwardPE: 18.0,
    pegRatio: 0.52,
    evEbitda: 14.2,
    priceToSales: 4.8,
    revenueGrowth: 45,
    marginTrend: 'Strong — gross margins above 50%',
    insiderActivity: 'Positive — recent insider buying at these levels',
    institutionalChange: '+$120M institutional position building',
    sharaiaCompliant: true,
    analystTarget: 26,
    analystCount: 6,
  },
  {
    id: 'lt-4',
    ticker: 'CRWD',
    company: 'CrowdStrike Holdings',
    sector: 'Cybersecurity',
    category: 'Strong Compounder',
    opportunityScore: 82,
    entryQuality: 'Good Entry',
    currentPrice: 322.40,
    change: 7.80,
    changePercent: 2.48,
    marketCap: '$77B',
    targetPrice: 420,
    upside: 30.3,
    aiThesis: 'CrowdStrike is executing a textbook platform expansion strategy. The Falcon platform started as endpoint detection and has systematically expanded into cloud security, identity protection, and now AI-driven threat intelligence. The key insight is that cybersecurity spending is moving from point solutions to consolidated platforms, and CRWD is positioned as the consolidation winner. Their net revenue retention above 120% demonstrates customers are expanding spend — not just renewing. The AI security opportunity is particularly underappreciated as enterprises need AI-native security tools to defend AI-native attack surfaces.',
    businessModel: 'Cloud-native cybersecurity platform (Falcon) providing endpoint, cloud, identity, and AI-powered threat intelligence. ARR-based model with high switching costs.',
    growthDrivers: ['Platform module expansion per customer', 'Cloud and identity security TAM expansion', 'AI-native threat detection differentiation', 'Federal and international market expansion', 'SMB market penetration via simplified packaging'],
    keyRisks: ['Competition from Microsoft Security suite', 'Enterprise budget fatigue for security spending', 'Incident response from July 2024 outage impact', 'Premium valuation limits multiple expansion'],
    fundamentalScore: 86,
    growthScore: 82,
    valuationScore: 65,
    catalystScore: 80,
    institutionalScore: 88,
    sustainabilityScore: 89,
    aiConfidenceScore: 84,
    riskScore: 74,
    forwardPE: 58.0,
    pegRatio: 1.28,
    evEbitda: 68.0,
    priceToSales: 18.2,
    revenueGrowth: 33,
    marginTrend: 'Expanding — operating leverage materializing',
    insiderActivity: 'Neutral — typical executive selling program',
    institutionalChange: '+$2.1B net institutional buying last two quarters',
    sharaiaCompliant: true,
    analystTarget: 385,
    analystCount: 38,
  },
  {
    id: 'lt-5',
    ticker: 'ARM',
    company: 'Arm Holdings',
    sector: 'Semiconductors',
    category: 'Fundamental Repricing',
    opportunityScore: 79,
    entryQuality: 'Neutral Entry',
    currentPrice: 148.60,
    change: 4.20,
    changePercent: 2.91,
    marketCap: '$156B',
    targetPrice: 195,
    upside: 31.2,
    aiThesis: 'ARM is a royalty-based architecture business being repriced as an AI infrastructure company. Every smartphone, server, and IoT device running ARM architecture pays a licensing fee. The AI opportunity is two-fold: ARM designs are increasingly used in AI inference chips due to superior power efficiency, and their royalty rates are being renegotiated upward as the value of the architecture increases. The market is still valuing ARM as a mobile chip company when it\'s becoming the foundational IP layer of AI infrastructure. This repricing thesis has significant runway.',
    businessModel: 'IP licensing company providing CPU architecture designs used by virtually every mobile chip and increasingly in AI/data center applications. Revenue from licensing and per-chip royalties.',
    growthDrivers: ['AI inference chip adoption driving higher royalty rates', 'Data center ARM deployment by cloud providers', 'Custom silicon trend benefiting ARM architecture', 'IoT proliferation royalty compounding', 'v9 architecture premium pricing uplift'],
    keyRisks: ['RISC-V long-term competitive threat', 'Concentration in mobile market', 'Softbank ownership overhang', 'Geopolitical risks in China licensing'],
    fundamentalScore: 82,
    growthScore: 78,
    valuationScore: 62,
    catalystScore: 84,
    institutionalScore: 80,
    sustainabilityScore: 85,
    aiConfidenceScore: 82,
    riskScore: 70,
    forwardPE: 72.0,
    pegRatio: 1.85,
    evEbitda: 55.0,
    priceToSales: 28.4,
    revenueGrowth: 48,
    marginTrend: 'Strong and expanding on licensing leverage',
    insiderActivity: 'Positive — management confidence in AI royalty thesis',
    institutionalChange: '+$3.4B institutional build since IPO',
    sharaiaCompliant: true,
    analystTarget: 172,
    analystCount: 24,
  },
];

export const PORTFOLIO_POSITIONS: PortfolioPosition[] = [
  {
    id: 'p-1',
    ticker: 'NVDA',
    company: 'NVIDIA Corporation',
    sector: 'Technology',
    shares: 50,
    avgCost: 620.00,
    currentPrice: 879.42,
    marketValue: 43971,
    unrealizedPL: 12971,
    unrealizedPLPercent: 41.8,
    weight: 28.4,
    dayChange: 617,
    dayChangePercent: 1.42,
    entryDate: '2024-01-15',
  },
  {
    id: 'p-2',
    ticker: 'PLTR',
    company: 'Palantir Technologies',
    sector: 'Technology',
    shares: 800,
    avgCost: 18.40,
    currentPrice: 24.82,
    marketValue: 19856,
    unrealizedPL: 5136,
    unrealizedPLPercent: 34.9,
    weight: 12.8,
    dayChange: 912,
    dayChangePercent: 4.81,
    entryDate: '2024-02-20',
  },
  {
    id: 'p-3',
    ticker: 'CRWD',
    company: 'CrowdStrike Holdings',
    sector: 'Technology',
    shares: 80,
    avgCost: 290.00,
    currentPrice: 322.40,
    marketValue: 25792,
    unrealizedPL: 2592,
    unrealizedPLPercent: 11.2,
    weight: 16.7,
    dayChange: 624,
    dayChangePercent: 2.48,
    entryDate: '2024-03-10',
  },
  {
    id: 'p-4',
    ticker: 'MSFT',
    company: 'Microsoft Corporation',
    sector: 'Technology',
    shares: 60,
    avgCost: 380.00,
    currentPrice: 420.14,
    marketValue: 25208,
    unrealizedPL: 2408,
    unrealizedPLPercent: 10.6,
    weight: 16.3,
    dayChange: 320,
    dayChangePercent: 1.29,
    entryDate: '2024-01-08',
  },
  {
    id: 'p-5',
    ticker: 'AEHR',
    company: 'Aehr Test Systems',
    sector: 'Semiconductors',
    shares: 2000,
    avgCost: 16.80,
    currentPrice: 14.20,
    marketValue: 28400,
    unrealizedPL: -5200,
    unrealizedPLPercent: -15.5,
    weight: 18.4,
    dayChange: 1700,
    dayChangePercent: 6.37,
    entryDate: '2024-04-02',
  },
  {
    id: 'p-6',
    ticker: 'AMZN',
    company: 'Amazon.com Inc.',
    sector: 'Technology',
    shares: 40,
    avgCost: 168.00,
    currentPrice: 185.40,
    marketValue: 7416,
    unrealizedPL: 696,
    unrealizedPLPercent: 10.4,
    weight: 4.8,
    dayChange: 148,
    dayChangePercent: 2.04,
    entryDate: '2024-03-25',
  },
];

export const NEWS_ITEMS: NewsItem[] = [
  {
    id: 'n-1',
    headline: 'Morgan Stanley Raises NVIDIA Price Target to $1,000, Cites Blackwell Demand Exceeding Supply',
    source: 'Morgan Stanley Research',
    ticker: 'NVDA',
    sentiment: 'bullish',
    urgency: 'high',
    catalystStrength: 88,
    publishedAt: '2 min ago',
    summary: 'Morgan Stanley analyst Joseph Moore increased PT to $1,000 from $850, maintaining Overweight rating. Checks indicate Blackwell GPU orders are tracking significantly ahead of initial supply availability.',
    aiAnalysis: 'This is a legitimate institutional catalyst, not noise. Morgan Stanley raising PT during active AI infrastructure buildout is meaningful. The supply constraint narrative actually strengthens the bull thesis — limited supply with surging demand equals sustained pricing power. High probability this catalyst drives institutional inflows today.',
    isNoise: false,
  },
  {
    id: 'n-2',
    headline: 'Palantir Wins $480M US Army Contract Extension for Maven Smart System',
    source: 'SEC Filing / DoD Announcement',
    ticker: 'PLTR',
    sentiment: 'bullish',
    urgency: 'high',
    catalystStrength: 82,
    publishedAt: '18 min ago',
    summary: 'Palantir announced a $480M contract extension with the US Army for the Maven Smart System AI targeting platform. Contract runs through 2027 with option years.',
    aiAnalysis: 'Material government contract win. At $480M, this is roughly 35% of PLTR\'s annual government revenue. The Maven Smart System is a flagship AI defense product — this extension signals high satisfaction and positions PLTR well for future defense AI expansions. Not noise — institutional trigger for position builds.',
    isNoise: false,
  },
  {
    id: 'n-3',
    headline: 'Fed Officials Signal Cautious Approach to Rate Cuts Amid Sticky Inflation Data',
    source: 'Federal Reserve / Bloomberg',
    ticker: 'SPY',
    sentiment: 'bearish',
    urgency: 'medium',
    catalystStrength: 65,
    publishedAt: '1 hr ago',
    summary: 'Several Fed officials commented that persistent inflation in services sector warrants patience before easing monetary policy.',
    aiAnalysis: 'Moderately negative macro signal but largely priced in. Market expects fewer cuts — this confirms existing expectations rather than surprising. Impact on growth stocks is limited given strong earnings fundamentals. Treat as background noise unless accompanied by stronger hawkish language from Powell.',
    isNoise: false,
  },
  {
    id: 'n-4',
    headline: 'CrowdStrike Reports 33% Revenue Growth, Raises Full-Year Guidance Above Consensus',
    source: 'Earnings Release',
    ticker: 'CRWD',
    sentiment: 'bullish',
    urgency: 'high',
    catalystStrength: 85,
    publishedAt: '3 hr ago',
    summary: 'CRWD Q1 FY2025 revenue of $921M beats estimates by $28M. ARR reaches $3.65B, up 33% YoY. FY2025 guidance raised across all metrics.',
    aiAnalysis: 'Strong beat and raise. The guidance raise is the key — it signals management visibility into continued demand. NRR above 120% confirms platform expansion is working. July 2024 incident concern appears fully behind them. This is a catalyst that institutional desks will use to add to positions on weakness.',
    isNoise: false,
  },
  {
    id: 'n-5',
    headline: 'Bitcoin ETF Inflows Hit $850M in Single Day as Institutional Adoption Accelerates',
    source: 'Bloomberg ETF',
    ticker: 'BTC',
    sentiment: 'bullish',
    urgency: 'medium',
    catalystStrength: 70,
    publishedAt: '4 hr ago',
    summary: 'Spot Bitcoin ETFs saw combined net inflows of $850M, led by BlackRock IBIT with $480M.',
    aiAnalysis: 'Significant institutional flow signal for crypto exposure. BlackRock IBIT leading inflows suggests pension fund and endowment-level capital entering. This is structural demand, not retail speculation. Bullish for crypto-adjacent equities (COIN, MSTR, MARA).',
    isNoise: false,
  },
];

export const WATCHLIST_GROUPS: WatchlistGroup[] = [
  {
    id: 'wl-1',
    name: 'AI Infrastructure',
    items: [
      { id: 'w-1', ticker: 'NVDA', company: 'NVIDIA', price: 879.42, change: 12.34, changePercent: 1.42, volume: 48200000, relVolume: 2.4, aiScore: 91, trend: 'bullish', catalyst: 'MS Upgrade', sector: 'Semiconductors' },
      { id: 'w-2', ticker: 'AMD', company: 'Advanced Micro Devices', price: 168.44, change: 3.82, changePercent: 2.32, volume: 62400000, relVolume: 1.6, aiScore: 78, trend: 'bullish', catalyst: 'MI300X demand', sector: 'Semiconductors' },
      { id: 'w-3', ticker: 'SMCI', company: 'Super Micro Computer', price: 893.50, change: 24.80, changePercent: 2.85, volume: 8900000, relVolume: 3.1, aiScore: 74, trend: 'bullish', catalyst: 'AI server win', sector: 'Technology' },
      { id: 'w-4', ticker: 'ANET', company: 'Arista Networks', price: 312.80, change: 6.20, changePercent: 2.02, volume: 4200000, relVolume: 1.4, aiScore: 82, trend: 'bullish', catalyst: 'AI networking', sector: 'Networking' },
    ],
  },
  {
    id: 'wl-2',
    name: 'Day Trading Watchlist',
    items: [
      { id: 'w-5', ticker: 'TSLA', company: 'Tesla', price: 249.80, change: -3.20, changePercent: -1.27, volume: 89400000, relVolume: 1.3, aiScore: 66, trend: 'bearish', catalyst: 'FSD update', sector: 'Auto' },
      { id: 'w-6', ticker: 'MSTR', company: 'MicroStrategy', price: 1580.20, change: 48.40, changePercent: 3.16, volume: 12800000, relVolume: 2.8, aiScore: 72, trend: 'bullish', catalyst: 'BTC rally', sector: 'Technology' },
      { id: 'w-7', ticker: 'COIN', company: 'Coinbase', price: 238.40, change: 12.80, changePercent: 5.67, volume: 18400000, relVolume: 2.2, aiScore: 77, trend: 'bullish', catalyst: 'ETF inflows', sector: 'Finance' },
      { id: 'w-8', ticker: 'META', company: 'Meta Platforms', price: 513.20, change: 8.75, changePercent: 1.74, volume: 22400000, relVolume: 1.8, aiScore: 81, trend: 'bullish', catalyst: 'Threads growth', sector: 'Technology' },
    ],
  },
  {
    id: 'wl-3',
    name: 'Long-Term Positions',
    items: [
      { id: 'w-9', ticker: 'PLTR', company: 'Palantir', price: 24.82, change: 1.14, changePercent: 4.81, volume: 42800000, relVolume: 2.1, aiScore: 84, trend: 'bullish', catalyst: 'DoD contract', sector: 'Software' },
      { id: 'w-10', ticker: 'CRWD', company: 'CrowdStrike', price: 322.40, change: 7.80, changePercent: 2.48, volume: 12400000, relVolume: 1.7, aiScore: 82, trend: 'bullish', catalyst: 'Beat & raise', sector: 'Cybersecurity' },
      { id: 'w-11', ticker: 'AEHR', company: 'Aehr Test Systems', price: 14.20, change: 0.85, changePercent: 6.37, volume: 4800000, relVolume: 3.4, aiScore: 78, trend: 'bullish', catalyst: 'SiC demand', sector: 'Semis Equip' },
      { id: 'w-12', ticker: 'ARM', company: 'Arm Holdings', price: 148.60, change: 4.20, changePercent: 2.91, volume: 8200000, relVolume: 1.5, aiScore: 79, trend: 'bullish', catalyst: 'AI royalties', sector: 'Semiconductors' },
    ],
  },
];

export const ALERTS: Alert[] = [
  { id: 'a-1', type: 'score', ticker: 'NVDA', message: 'NVDA opportunity score upgraded to 91 — Elite Setup', urgency: 'high', timestamp: '2 min ago', read: false },
  { id: 'a-2', type: 'breakout', ticker: 'SMCI', message: 'SMCI breaking above Opening Range High at $892', urgency: 'high', timestamp: '8 min ago', read: false },
  { id: 'a-3', type: 'volume', ticker: 'COIN', message: 'COIN unusual volume detected: 2.2x relative volume', urgency: 'medium', timestamp: '15 min ago', read: false },
  { id: 'a-4', type: 'earnings', ticker: 'CRWD', message: 'CRWD beat & raise — guidance above consensus', urgency: 'high', timestamp: '3 hr ago', read: true },
  { id: 'a-5', type: 'regime', ticker: 'SPY', message: 'Market Regime confirmed Neutral Bullish — risk appetite improving', urgency: 'medium', timestamp: '4 hr ago', read: true },
];

export const SECTOR_PERFORMANCE = [
  { name: 'Technology', change: 1.82, color: '#22c55e' },
  { name: 'Semiconductors', change: 2.41, color: '#22c55e' },
  { name: 'Cybersecurity', change: 1.95, color: '#22c55e' },
  { name: 'Energy', change: 0.48, color: '#22c55e' },
  { name: 'Healthcare', change: -0.22, color: '#ef4444' },
  { name: 'Finance', change: 0.15, color: '#22c55e' },
  { name: 'Consumer Disc', change: -0.88, color: '#ef4444' },
  { name: 'Utilities', change: -1.24, color: '#ef4444' },
];

export const AI_MARKET_COMMENTARY = `The market is exhibiting classic Neutral Bullish behavior with concentrated strength in mega-cap technology and AI infrastructure names. Institutional flows remain firmly concentrated in the NVDA/AMD/MSFT AI infrastructure trade, with breadth narrowing slightly — a pattern consistent with late-cycle rotation within a bull trend rather than distribution.

The VIX at 14.72 signals complacency is returning, but this level remains historically compatible with continued upside in index-level products. The real opportunity today is in identifying which second-tier AI infrastructure names are beginning to attract institutional attention before the mainstream narrative catches up.

Key risk to monitor: small caps (IWM -0.44%) are underperforming, which suggests the rally remains largely concentrated. This is not yet a warning signal but bears watching — broad market participation would be needed for sustained momentum beyond current levels.

AI Inference thesis is gaining momentum: as hyperscalers complete training infrastructure buildout, the next spending wave will be inference optimization — benefiting ARM, QCOM, and emerging edge AI plays.`;
